name: marketplace-hello-world

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"
          
      - name: Print Production Environment Variable
        run:  echo "The current environment is: ${{ vars.MY_ENVIRONMENT }}"

  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Trivy version
        run: |
          trivy --version

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
