name: marketplace-hello-world

on:
  push:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: production
    

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"

    steps:
      - name: Print Production Environment Variable
        run:  echo "The current environment is: ${{ vars.MY_ENVIRONMENT }}"
